sudo: required
language: java
before_install:
    - chmod +x .travis/before_test.sh
install: .travis/before_test.sh
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7
env:
    - MARIA_VERSION=5.5 MAX_ALLOWED_PACKET=8M INNODB_LOG_FILE_SIZE=32M
    - MARIA_VERSION=5.5 MAX_ALLOWED_PACKET=16M INNODB_LOG_FILE_SIZE=64M
    - MARIA_VERSION=5.5 MAX_ALLOWED_PACKET=32M INNODB_LOG_FILE_SIZE=128M
    - MARIA_VERSION=10.0 MAX_ALLOWED_PACKET=8M INNODB_LOG_FILE_SIZE=32M
    - MARIA_VERSION=10.0 MAX_ALLOWED_PACKET=16M INNODB_LOG_FILE_SIZE=64M
    - MARIA_VERSION=10.0 MAX_ALLOWED_PACKET=32M INNODB_LOG_FILE_SIZE=128M
    - MARIA_VERSION=10.1 MAX_ALLOWED_PACKET=8M INNODB_LOG_FILE_SIZE=32M
    - MARIA_VERSION=10.1 MAX_ALLOWED_PACKET=16M INNODB_LOG_FILE_SIZE=64M
    - MARIA_VERSION=10.1 MAX_ALLOWED_PACKET=32M INNODB_LOG_FILE_SIZE=128M
    - MYSQL_VERSION=5.7 MAX_ALLOWED_PACKET=8M INNODB_LOG_FILE_SIZE=32M
    - MYSQL_VERSION=5.7 MAX_ALLOWED_PACKET=16M INNODB_LOG_FILE_SIZE=64M
    - MYSQL_VERSION=5.7 MAX_ALLOWED_PACKET=32M INNODB_LOG_FILE_SIZE=128M
    - MYSQL_VERSION=5.6 MAX_ALLOWED_PACKET=8M INNODB_LOG_FILE_SIZE=32M
    - MYSQL_VERSION=5.6 MAX_ALLOWED_PACKET=16M INNODB_LOG_FILE_SIZE=64M
    - MYSQL_VERSION=5.6 MAX_ALLOWED_PACKET=32M INNODB_LOG_FILE_SIZE=128M
script: mvn test $ADDITIONNAL_VARIABLES -DjobId=$TRAVIS_JOB_ID
cache:
    directories:
        - $HOME/.m2
        - /var/cache/apt/archives
